---
title: Aeon Arts
timezone: America/Los_Angeles
collections:
  Default:
    title: Default
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: multiverse_jekyll_theme
exclude:
- Gemfile.lock
- node_modules
